### ISSUE TITLE
License isn't Open Source

### ISSUE THREAD

**Issue by palob** [moduloteam/MOSL#1]
In case you aren't aware of due to [3a](https://github.com/moduloproject/MOSL#a-commercial-use) your licence isn't [Open Source](http://opensource.org/osd) as per the OSI definition nor it is [Free Software](http://www.gnu.org/philosophy/free-sw.html) according to the FSF.

May I ask why you want to create a new licence instead of using one of [those](http://www.gnu.org/licenses/licenses.html) for your projects?

Generally I don't think it is the wisest decision to create one without legal advice or without being a lawyer.

**Comment by deadbaed** [comment]
Hey :)
We wrote this license very quickly, but we don't use it anymore. We just don't delete try repo because reasons :)

**Comment by palob** [comment]
Alright :+1:
